// Generated by CoffeeScript 1.10.0
(function() {
  var ctx, plot, updateChart;

  console.log("charting");

  ctx = $('#chart').get(0).getContext('2d');

  window.ctx = ctx;

  updateChart = function(data) {
    var i, j, len;
    ctx.beginPath();
    ctx.fillStyle = 'black';
    for (j = 0, len = data.length; j < len; j++) {
      i = data[j];
      ctx.rect(i.x * 100 + 200, i.y * 100 + 200, 1, 1);
    }
    return ctx.fill();
  };

  plot = function(fcn) {
    var j, x, y;
    ctx.beginPath();
    ctx.fillStyle = 'red';
    for (x = j = 0; j <= 400; x = ++j) {
      y = fcn(x / 100 - 2) * 100 + 200;
      ctx.rect(x, y, 1, 1);
    }
    return ctx.fill();
  };

  plot(function(x) {
    return 0.5 * Math.sin(x);
  });

  setInterval(function() {
    console.log(window.robot.history.length);
    updateChart(window.robot.history);
    return window.robot.history = [];
  }, 1000);

}).call(this);
