// Generated by CoffeeScript 1.10.0
(function() {
  var colors, ctx, curColor, plot, pointCounter, updateChart;

  console.log("charting");

  ctx = $('#chart').get(0).getContext('2d');

  window.ctx = ctx;

  colors = ['#890000', '#ae3d00', '#ba9600', '#3b5828', '#014c63', '#18121e', '#233237', '#984b43', '#eac67a', '#7a327e'];

  curColor = colors.pop();

  pointCounter = 0;

  updateChart = function(data) {
    var i, j, len;
    ctx.beginPath();
    ctx.strokeStyle = curColor || 'blue';
    for (j = 0, len = data.length; j < len; j++) {
      i = data[j];
      ctx.lineTo(i.x * 100 + 200, i.y * 100 + 200);
    }
    return ctx.stroke();
  };

  plot = function(fcn) {
    var j, x, y;
    ctx.beginPath();
    ctx.fillStyle = 'grey';
    for (x = j = 0; j <= 400; x = ++j) {
      y = fcn(x / 100 - 2) * 100 + 200;
      ctx.rect(x, y, 3, 3);
    }
    return ctx.fill();
  };

  setInterval(function() {
    updateChart(window.robot.history);
    return window.robot.history = [];
  }, 200);

  $('#reset').click(function() {
    curColor = colors.pop();
    window.robot.history = [];
    return ctx.moveTo(-100, -100);
  });

}).call(this);
