// Generated by CoffeeScript 1.10.0
(function() {
  var ControlledRobot, L, Robot, canvas, h, rect, robot, target, target2,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  h = 0.1;

  L = 10;

  Robot = (function() {
    function Robot(L1, canvasObj) {
      this.L = L1;
      this.canvasObj = canvasObj;
      this.randomizePosition();
      this.render();
    }

    Robot.prototype.randomizePosition = function() {
      this.x = Math.random() * 600;
      this.y = Math.random() * 400;
      return this.theta = Math.random() * 2 * Math.PI;
    };

    Robot.prototype.update = function(speed, angle) {
      this.x += speed * Math.cos(this.theta) * Math.cos(angle) * h;
      this.y += speed * Math.sin(this.theta) * Math.cos(angle) * h;
      return this.theta += Math.atan2(Math.sin(speed * angle), this.L) * h;
    };

    Robot.prototype.render = function() {
      this.canvasObj.setAngle(this.theta * 180 / Math.PI).set({
        originX: 'center',
        originY: 'center',
        left: this.x,
        top: this.y
      });
      return canvas.renderAll();
    };

    return Robot;

  })();

  ControlledRobot = (function(superClass) {
    extend(ControlledRobot, superClass);

    function ControlledRobot(L1, canvasObj, distControl, targetControl, alignControl) {
      this.L = L1;
      this.canvasObj = canvasObj;
      this.distControl = distControl;
      this.targetControl = targetControl;
      this.alignControl = alignControl;
      ControlledRobot.__super__.constructor.call(this, this.L, this.canvasObj);
    }

    ControlledRobot.prototype.update = function(goalX, goalY, goalTheta) {
      var alignHeading, directionToGoal, dist, targetHeading;
      dist = Math.sqrt(Math.pow(this.x - goalX, 2) + Math.pow(this.y - goalY, 2));
      directionToGoal = Math.atan2(goalY - this.y, goalX - this.x);
      targetHeading = directionToGoal - this.theta;
      alignHeading = directionToGoal - goalTheta;
      return ControlledRobot.__super__.update.call(this, this.distControl * dist, this.targetControl * targetHeading + this.alignControl * alignHeading);
    };

    return ControlledRobot;

  })(Robot);

  canvas = new fabric.Canvas('cvs').setHeight(400).setWidth(600);

  rect = new fabric.Rect({
    width: 30,
    height: 20
  });

  target = new fabric.Circle({
    left: 300 - 10,
    top: 200 - 10,
    radius: 10,
    fill: 'crimson'
  });

  target2 = new fabric.Circle({
    left: 300 - 5,
    top: 200 - 5,
    radius: 5,
    fill: 'black'
  });

  canvas.add(rect, target, target2);

  robot = new ControlledRobot(1, rect, 0.05, 0.1, 0.1);

  setInterval(function() {
    robot.update(300, 200, -Math.PI / 2);
    return robot.render();
  }, 16);

  $('#reset').click(function() {
    return robot.randomizePosition();
  });

}).call(this);
